
CREATE TABLE IF NOT EXISTS users (
id SERIAL PRIMARY KEY,
login TEXT NOT NULL UNIQUE,
password_hash TEXT NOT NULL,
nickname TEXT NOT NULL UNIQUE,
firstname TEXT,
lastname TEXT,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
deleted_at TIMESTAMP
);
CREATE TABLE IF NOT EXISTS message (
id SERIAL PRIMARY KEY,
body TEXT NOT NULL,
from_id INT,
chat_id INT,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS attachments (
id SERIAL PRIMARY KEY,
message_id INT NOT NULL,
url TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS chat_users (
id SERIAL PRIMARY KEY,
chat_id INT NOT NULL,
user_id INT NOT NULL
);
CREATE TABLE IF NOT EXISTS chat (
id SERIAL PRIMARY KEY,
user_count INT NOT NULL,
name TEXT,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
