version: '3.8'

services:
  db:
    image: postgres:16.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5


  app:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:admin@db:5432/mydatabase?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    ports:
      - "8888:8888"

volumes:
  db_data:

networks:
  app-network: